# Generated by Django 2.2 on 2019-04-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a title', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a title for the project', max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('source', models.URLField(default='')),
                ('image', models.ImageField(default='img/banff_mountain.jpg', upload_to='img/project_thumbnails')),
            ],
        ),
    ]
