# Generated by Django 2.1.5 on 2019-03-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='img/banff_mountain.jpg', upload_to='img/project_thumbnails'),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(default=''),
        ),
    ]
