# Generated by Django 2.1 on 2018-10-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a title for the project', max_length=200)),
                ('description', models.TextField()),
                ('photo_category', models.CharField(choices=[('PE', 'People'), ('LA', 'Landscape'), ('CL', 'Close-up'), ('FD', 'Food'), ('MS', 'Misc')], default='MS', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
