# Generated by Django 2.2 on 2019-04-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='img/banff_mountain.jpg', upload_to='img/projectthumbnails'),
        ),
    ]
