# Generated by Django 2.1 on 2018-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_photo_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(default='apps/static/img/banff_mountain.jpg', upload_to='apps/static/img/photos'),
        ),
    ]
