# Generated by Django 2.1 on 2018-10-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20181009_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(help_text='Enter a title', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(default='apps/static/img/banff_mountain.jpg', upload_to=''),
        ),
    ]
