# Generated by Django 2.1.3 on 2019-01-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20181010_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='project',
            name='pic',
            field=models.ImageField(default='apps/static/img/banff_mountain.jpg', upload_to=''),
        ),
    ]
